#!/usr/bin/python3
# SPDX-License-Identifier: BSD-3-Clause

import sys
import math


def tonum(s):
    try:
        return int(s)

    except:
        return float(s)

ans = 0
for line in sys.stdin:
    line = line.rstrip()
    num = tonum(line)

    ans = math.sqrt(num)

print(ans)
